source 'https://rubygems.org' do
  gem 'activerecord', require: 'active_record'
  gem 'awesome_print'
  gem 'pry'
  gem 'pry-byebug'
  gem 'puma'
  gem 'racksh'
  gem 'rake'
  gem 'redis'
  gem 'require_all'
  gem 'shotgun'
  gem 'sidekiq'
  gem 'sinatra-activerecord', require: 'sinatra/activerecord'
  gem 'sqlite3'
  gem 'sinatra', require: 'sinatra/base'
end
